### ISSUE TITLE
Import of pep datas from Metronome blocks Prosody

### ISSUE THREAD

**Issue by anubister** [anubister/prosody_ynh#12]
```
Nov 16 21:57:56 c2s5851c50      error   Traceback[c2s]: /usr/lib/prosody/util/pubsub.lua:188: bad argument #1 to 'for iterator' (table expected, got nil)
        stack traceback:
        [C]: in function 'next'
        /usr/lib/prosody/util/pubsub.lua:188: in function 'util.pubsub.new'
        /usr/lib/prosody/modules/mod_pep.lua:221: in field 'get_pep_service'
        /usr/lib/prosody/modules/mod_bookmarks.lua:350: in field '?'
        /usr/lib/prosody/util/events.lua:81: in function </usr/lib/prosody/util/events.lua:77>
        (...tail calls...)
        /usr/lib/prosody/core/sessionmanager.lua:230: in function 'core.sessionmanager.bind_resource'
        /usr/lib/prosody/modules/mod_saslauth.lua:359: in field '?'
        /usr/lib/prosody/util/events.lua:81: in function </usr/lib/prosody/util/events.lua:77>
        (...tail calls...)
        /usr/lib/prosody/core/stanza_router.lua:143: in upvalue 'core_process_stanza'
        /usr/lib/prosody/modules/mod_c2s.lua:326: in upvalue 'func'
        /usr/lib/prosody/util/async.lua:144: in function </usr/lib/prosody/util/async.lua:142>

```
Probably a format incompatibility between Metronome and Prosody, blocking prosody start.

**Comment by mwild1** [comment]
Almost certainly a problem with the data format. I'm pretty sure Prosody didn't even have PEP storage when Metronome was forked, so they are going to differ.

**Comment by anubister** [comment]
fixed by [c95b945](https://github.com/anubister/prosody_ynh/commit/c95b945181eabd461e704f2079957fb9d226fe85)

**Comment by mwild1** [comment]
This is marked as fixed, but it looks like there is no migration of PEP data? This could be a big problem and cause data loss - things like group chats, OMEMO keys, etc. would be lost after switching to Prosody.

**Comment by linkmauve** [comment]
Hi, I implemented a proper solution here: https://modules.prosody.im/mod_storage_metronome_readonly

It isn’t only for PEP, but for all data stores I could find in a random Metronome install from Yunohost.  Only the HTTP File Upload data still needs manual changes, since the files have to be moved.

Please reopen this issue until you switch it to use this method instead.
