### ISSUE TITLE
Missing certificate for "pubsub.DOMAIN" 

### ISSUE THREAD

**Issue by pitchum** [anubister/prosody_ynh#19]
Running `prosodyctl check certs` indicates that some  server-to-server connections may have problems because of invalid certificate.

```
# prosodyctl check certs
Checking certificates...
Checking certificate for mydomain.net
  Certificate: /etc/yunohost/certs/mydomain.net/crt.pem
Checking certificate for localhost
certmanager         info        No certificate present in SSL/TLS configuration for localhost. SNI will be required.
  No 'certificate' found for localhost
Checking certificate for pubsub.mydomain.net
  Certificate: /etc/yunohost/certs/mydomain.net/crt.pem
    Not valid for server-to-server connections to pubsub.mydomain.net.
Checking certificate for xmpp-upload.mydomain.net
  Certificate: /etc/yunohost/certs/mydomain.net/crt.pem
Checking certificate for muc.mydomain.net
  Certificate: /etc/yunohost/certs/mydomain.net/crt.pem
```

**Comment by pitchum** [comment]
Closing this issue since development now continues on https://github.com/YunoHost-Apps/prosody_ynh/ (branch testing). Reopen issue there if needed.

(A possible fix has already been pushed in https://github.com/YunoHost-Apps/prosody_ynh/commit/36bdb12e072c4152c515cdca8fc5a26f8d90049a )

**Comment by blogdemoi** [comment]
> Closing this issue since development now continues on https://github.com/YunoHost-Apps/prosody_ynh/ (branch testing). Reopen issue there if needed.
> 
> (A possible fix has already been pushed in [YunoHost-Apps@36bdb12](https://github.com/YunoHost-Apps/prosody_ynh/commit/36bdb12e072c4152c515cdca8fc5a26f8d90049a) )

Hi, should I uninstall the anubister version and install the https://github.com/YunoHost-Apps/prosody_ynh/ (branch testing) if development continues there? Does it provide the same functionalities out of the box?
Thank you.

**Comment by pitchum** [comment]
Hi, sorry for the late reply.

> Hi, should I uninstall the anubister version and install the https://github.com/YunoHost-Apps/prosody_ynh/ (branch testing) if development continues there?

Yes.

Normally, uninstalling the app should not remove data, but if you want to be sure, make a copy of `/var/lib/prosody` before. After installation of the new testing version, you may have permissions issues on that directory (because the new "prosody" unix account may have a new uid). If it happens, just run the following command after install :

    chown -R prosody: /var/lib/prosody


> Does it provide the same functionalities out of the box? Thank you.

Yes, and more, of course :)
If it's not the case, please open new issues.
