### ISSUE TITLE
Using prosody package from Debian instead of building from sources

### ISSUE THREAD

**Issue by pitchum** [anubister/prosody_ynh#5]
As I started involving myself in this app, I was considering rewriting scripts so as to use official prosody packages from Debian instead of building from source.
I think it would make sense since Yunohost is based on Debian.

Using Debian packages as more pros than cons IMHO.
Pros:

- Debian's maintainers already do a good job of proper integration, so we wouldn't have to repeat it (filetree structures, maintenance scripts,...)
- reproducible installs
- no need to install a lot of "*-dev" packages on a production machine
- automatically benefit from Debian's security updates

Cons:

- less bleeding edge versions of software (but who really cares? :) )

**Comment by anubister** [comment]
Rather OK with that (historically when I started to work on this topic on Yunohost 11 it was defintely not possible as Prosody Debian package was really outdated). 
- To check if  Debian prosody and modules package (0.12.3 and 0.0~hg20230223.556bf57d6417+dfsg-1)  https://prosody.im/doc/release/0.12.4 are sufficient wrt targeted supported XEP.
- I have currently not much time for this deep change, feel free to provide a dedicated branch for this.

**Comment by anubister** [comment]
Thanks for your work pitchum, 
my old package is now moved in the branch "install-from-source".
your implementation is now in "install-from-debian", which is the one used for "master" since now.
